version: '3'
services:
  apigateway:
    image: gwangjang/apigateway
    networks:
      - msa-network

  eureka:
    image: gwangjang/eureka:latest
    networks:
      - msa-network

  contents:
    image: gwangjang/contents
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    ports:
      - 8084:8084
    networks:
      - msa-network
    build: ./ContentsService

networks:
  msa-network:
    external: true
