version: '3'
services:
  contents:
    image: gwangjang/contents
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://3.34.93.53:8761/eureka/
    ports:
      - 8084:8084
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
